config/routes.rb
#custom routes for this plugin
resources :helpdesk_tickets, :only => [:edit, :destroy, :update]

resources :projects do
  resources :canned_responses, :only => [:new, :create]
end

resources :canned_responses do
  collection do
    post :add 
  end
end

match "helpdesk_mailer" => "helpdesk_mailer#index"
match "helpdesk_mailer/get_mail" => "helpdesk_mailer#get_mail"
match "helpdesk/save_settings" => "helpdesk#save_settings"
match "helpdesk/get_mail" => "helpdesk#get_mail"
match "helpdesk/delete_spam/:id" => "helpdesk#delete_spam"
match "helpdesk/email_note.:format" => "helpdesk#email_note"
match "helpdesk/create_ticket.:format" => "helpdesk#create_ticket"
match "helpdesk/show_original" => "helpdesk#show_original"
match "helpdesk/:action" => 'helpdesk'
match "helpdesk_reports/:action/(:project_id)" => 'helpdesk_reports'

get "mail_fetcher/receive_imap" => "mail_fetcher#receive_imap"
get "mail_fetcher/receive_pop3" => "mail_fetcher#receive_pop3"

match 'tickets/:id/:hash' => 'public_tickets#show', :as => :public_ticket
match 'tickets/:id/add_comment/:hash' => 'public_tickets#add_comment', :as => :public_ticket_add_comment

app/views/issues/_helpdesk_customer_profile.html.erb
<%  if !@issue.blank? && User.current.allowed_to?(:view_helpdesk_tickets, @project) %>
<span id="cusomer_profile_and_issues">
		<div id="customer_profile">
			<div class="contextual">    
				<%= link_to l(:button_update), 
					{:controller => 'helpdesk_tickets',
					:action => 'edit',
					:issue_id => @issue},
					:remote => true if User.current.allowed_to?(:edit_helpdesk_tickets, @project) %>
	
			 </div>
			<h3><%= l(:label_helpdesk_customer_profile) %></h3>
			<% unless !(@show_form == "true") %>
				<%= form_for @helpdesk_ticket, :url => {:controller => 'helpdesk_tickets',
		          	              	:action => 'update',
		     	                    :issue_id => @issue},
		                    		:html => {:id => 'ticket_data_form',
		                    							:method => :put} do |f| %>

				<% unless @helpdesk_ticket.new_record? %>
					<div class="contextual">  
					<%= link_to image_tag('link_break.png'),
	                                {:controller => 'helpdesk_tickets', :action => 'destroy', :id => @helpdesk_ticket},
	                                :method => :delete,
	                                :data => {:confirm => l(:text_are_you_sure)},
	                                :title => l(:label_relation_delete) %>
	        </div>          
        <% end %>
        	<p class="contact_auto_complete"><%= label_tag :helpdesk_ticket_contact_id,  l(:label_helpdesk_customer)%><br>
  					<%= select_contact_tag('helpdesk_ticket[contact_id]', @helpdesk_ticket.customer, :is_select => Contact.visible.by_project(@project).count < 50, :include_blank => false, :add_contact => true, :display_field => @helpdesk_ticket.customer.blank?) %>
        	</p>

					<p><%= label_tag :helpdesk_ticket_source,  l(:label_helpdesk_ticket_source)%><br>
						<%= f.select :source, helpdesk_tickets_source_for_select %></p>

				  <p><%= f.text_field :ticket_date, :size => 12, :required => true, :value => @helpdesk_ticket.ticket_date.to_date, :label => l(:label_helpdesk_ticket_date) %> <%= f.text_field :ticket_time, :value => @helpdesk_ticket.ticket_date.to_s(:time), :size => 5 %><%= calendar_for('helpdesk_ticket_ticket_date') %> </p>

					
					<%= submit_tag l(:button_update) %>
					<%= link_to l(:button_cancel), {}, :onclick => "$('#ticket_data_form').hide(); return false;" %>						

				<% end %>		                    	

			<% end %>
	
			<span class="small-card">
				<%= render :partial => 'contacts/contact_card', :object => @issue.customer if @issue.customer %>
			</span>
		</div>
	
		<% if @issue.customer && (issues_count = @issue.customer.tickets.visible.count) - 1 > 0 %>
		<div id="customer_previous_issues">  
		<style type="text/css">
			#customer_previous_issues ul {margin: 0;  padding: 0;}
			#customer_previous_issues li {list-style-type:none; margin: 0px 2px 0px 0px; padding: 0px 0px 0px 0px;}
		</style>		
			<h3><%= l(:label_helpdesk_previous_issues) %> </h3>  
			
			<ul>
				<% (@issue.customer.tickets.visible.order("#{Issue.table_name}.status_id, #{Issue.table_name}.updated_on DESC").first(11) - [@issue]).each do |issue| %>   
				<li>  
					<%= link_to_issue(issue, :truncate => 60, :project => (@project != issue.project)) %> 			
				 </li>   			
				<% end %>    
			</ul>
			<div class="contextual">
				<%= link_to l(:label_issue_view_all) + " (#{issues_count})", {:controller => 'issues', 
								 :action => 'index', 
								 :set_filter => 1, 
								 :f => [:customer, :status_id], 
								 :v => {:customer => [@issue.customer.id]},
								 :op => {:customer => '=', :status_id => '*'}} %>
			</div>	 
		</div>    
		<% end %>
	
	</span>	
<% end %>

app/views/issues/_send_response.html.erb
<% if authorize_for(:issues, :send_helpdesk_response) && @issue.customer && @issue.customer.primary_email %>
<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		toggleSendMail($('#helpdesk_is_send_mail').get(0));

		var contactsEmails = ['<%= @issue.contacts.map{|c| c.primary_email if c.primary_email}.compact.uniq.join("\',\'").html_safe if @issue.contacts %>'];
		
		$("#helpdesk_cc").tagit({ availableTags: contactsEmails });
		$("#helpdesk_bcc").tagit({ availableTags: contactsEmails });		

    $('#email_footer').insertAfter($('#helpdesk_is_send_mail').parents().eq(1).find('.jstEditor'));
    $('#email_header').insertBefore($('#helpdesk_is_send_mail').parents().eq(1).find('>legend'));
    $('#email_canned_responses').insertBefore($('#helpdesk_is_send_mail').parents().eq(1).find('>legend'));
	});

  var issue_status = $('#issue_status_id').val();

	function toggleSendMail(element) {
		if (element.checked) {
      $('.email-template').show();
      <% unless HelpdeskSettings[:helpdesk_answered_status, @project].blank? %>  
        issue_status = $('#issue_status_id').val();  
		    $('#issue_status_id').val("<%= HelpdeskSettings[:helpdesk_answered_status, @project] %>");		
      <% end %>
       
		} else {
		  $('.email-template').hide();
      $('#cc_list_edit').hide();
      $('#issue_status_id').val(issue_status);
		}

	}  

function updateCannedResposeFrom(url, value) {
  $.ajax({
    url: url,
    type: 'post',
    data: {id: value}
  });
}


</script>
  
<% if CannedResponse.visible.any? %>
  <span id="email_canned_responses" style="display: none; float:right;" class="email-template">
    <%= select_tag 'helpdesk[canned_response]', options_for_select([[ "--- #{l(:label_helpdesk_canned_response_plural)} ---", '' ]] + CannedResponse.visible.order("#{CannedResponse.table_name}.name").map{|cr| [cr.name, cr.id]}), :onchange => "updateCannedResposeFrom('#{escape_javascript add_canned_responses_path(:project_id => @project, :issue_id => @issue, :format => 'js')}', $(this).val())"  %>
  </span>
<% end %>

<% unless HelpdeskSettings[:helpdesk_emails_header, @project].blank? %>
	<div id="email_header" style="display: none;" class="email-template">
		<%= textilizable(HelpdeskMailer.apply_macro(HelpdeskSettings[:helpdesk_emails_header, @project], @issue.customer, @issue, User.current)).html_safe  %>
	</div>
<% end %>

<% unless HelpdeskSettings[:helpdesk_emails_footer, @project].blank? %>
	<div id="email_footer" style="display: none;" class="email-template">
		<%= textilizable(HelpdeskMailer.apply_macro(HelpdeskSettings[:helpdesk_emails_footer, @project], @issue.customer, @issue, User.current)).html_safe  %>
	</div>
<% end %>

<p id="helpdesk_send_response">  
  <%= check_box_tag 'helpdesk[is_send_mail]', 1, HelpdeskSettings[:send_note_by_default, @project], :onclick => "toggleSendMail(this);" %>
  <%= label_tag :helpdesk_is_send_mail, l(:label_is_send_mail), :class => "icon icon-email-to", :style => "" %>
  
  <span id="journal_contacts" style="display: none;" class="email-template">
      <%= contact_tag(@issue.customer) %>
      <span id="customer_to_email"> (<%= @issue.helpdesk_ticket.default_to_address %>)</span>
        <%= select_tag 'helpdesk[to_address]', options_for_select(@issue.helpdesk_ticket.available_addresses), {:style => "display:none;"} %>
      <% if @issue.customer.emails.count > 1 %>
		    <a href="#" class="inline-edit" onclick="$('#customer_to_email').hide(); $(this).hide(); $('#helpdesk_to_address').show(); return false;"><img alt="Edit" src="/images/edit.png" style="vertical-align:middle;" ></a>	
      <% end %>
  </span>
  <br/>
  <span class="search_for_watchers email-template" id="add_cc" style="display: none;" >
    <%= link_to l(:label_helpdesk_add_cc), '#', :onclick => "$('#cc_list_edit').show(); $('#add_cc').hide(); $('#helpdesk_is_cc').val(1); return false;" %>
  </span>
</p>

<div id="cc_list_edit" style="display:none;" >
	<%= hidden_field_tag 'helpdesk[is_cc]' %>
	<p class="cc-list-edit">  
		<span class="is-cc">
		<%= label_tag l(:label_helpdesk_cc) %>
	  </span>
	  <%= text_field_tag 'helpdesk[cc_list]',  @issue.helpdesk_ticket.cc_addresses.join(','),  :size => 10, :class => 'hol', :id => "helpdesk_cc" %>
	</p>
	<div style="clear: both;"></div>
	<p class="cc-list-edit">  
		<span class="is-cc">
	  <%# check_box_tag 'helpdesk[is_bcc]', 1, false, :onclick => "$('#bcc_list_edit ul.tagit').toggle();" %>
		<%= label_tag l(:label_helpdesk_bcc) %>
	  </span>
	  <%= text_field_tag 'helpdesk[bcc_list]', "",  :size => 10, :class => 'hol', :id => "helpdesk_bcc" %>
	</p>
	<div style="clear: both;"></div>
</div>

<% end %>

<% content_for :header_tags do %>
	<%= javascript_include_tag :helpdesk, :plugin => 'redmine_contacts_helpdesk'  %>
  <%= javascript_include_tag :"tag-it", :plugin => 'redmine_contacts'  %>
  <%= stylesheet_link_tag :"jquery.tagit.css", :plugin => 'redmine_contacts' %>	
	<%= stylesheet_link_tag :contacts, :plugin => 'redmine_contacts' %>
	<%= stylesheet_link_tag :helpdesk, :plugin => 'redmine_contacts_helpdesk' %>
<% end %>

app/views/issues/_ticket_data.html.erb
<% if User.current.allowed_to?(:view_helpdesk_tickets, @project) && @issue.customer  %>
<div id="ticket_data">
    <div class="contextual">    
        <%= link_to l(:label_helpdesk_public_link), public_ticket_path(@issue.helpdesk_ticket, :hash => @issue.helpdesk_ticket.token), :class => "icon icon-public-link" if RedmineHelpdesk.public_tickets? %>
        <%= link_to l(:label_helpdesk_spam), 
          {:controller => 'helpdesk',
          :action => 'delete_spam',
          :project_id => @project,
          :issue_id => @issue},
          :method => :delete,
          :data => {:confirm => l(:text_are_you_sure)},          
          :class => "icon icon-email-spam" if @issue.helpdesk_ticket.source == HelpdeskTicket::HELPDESK_EMAIL_SOURCE && @issue.customer.primary_email && User.current.allowed_to?(:send_response, @project) && User.current.allowed_to?(:delete_issues, @project) && User.current.allowed_to?(:delete_contacts, @project) %>
    </div>
	<span class="icon <%= helpdesk_ticket_source_icon(@issue.helpdesk_ticket) %>">
		<%=  l(:label_helpdesk_from) %>
	</span>
	<span class="ticket_customer"  style="white-space: nowrap;display: inline-block;">
	  <%= contact_tag(@issue.customer, :type => "plain") %>
	  (<%= @issue.helpdesk_ticket.from_address %>)
	</span>
    <% if attachment = @issue.helpdesk_ticket.message_file %>
      <span class="attachment" style="white-space: nowrap;display: inline-block;">
        <%= link_to_attachment attachment, :text => l(:label_helpdesk_original), :class => 'icon icon-attachment' -%>
        <%= h(" - #{attachment.description}") unless attachment.description.blank? %>
          <span class="size">(<%= number_to_human_size attachment.filesize %>)</span>
          <%= link_to_if_authorized image_tag('magnifier.png', :plugin => "redmine_contacts_helpdesk"),
                :controller => 'helpdesk', :action => 'show_original',
                :id => attachment, :project_id => @project %>
      </span> 
    <% end %>	
    <span class="helpdesk-message-date"><%= format_time(@issue.helpdesk_ticket.ticket_date) %></span> 
    <br>
    <% unless @issue.helpdesk_ticket.cc_address.blank? %>
    <span class="helpdesk-message-date"><%=  l(:label_helpdesk_cc) %>: <%= @issue.helpdesk_ticket.cc_address.split(',').join(', ') %></span>      
    <% end %>
</div>
<hr />
<% end %>

app/views/issues/_ticket_data_form.html.erb
<% if @issue.new_record? && !@copy_from && User.current.allowed_to?(:edit_helpdesk_tickets, @project) && @issue.tracker_id.to_s == HelpdeskSettings[:helpdesk_tracker, @project.id] %>

  <p><%= label_tag :helpdesk_ticket_contact_id,  l(:label_helpdesk_customer) %>
    <%= select_contact_tag('helpdesk_ticket[contact_id]', @issue.helpdesk_ticket.try(:customer), :is_select => Contact.visible.by_project(@project).count < 50, :include_blank => true, :add_contact => true, :display_field => @issue.helpdesk_ticket.try(:customer).blank?) %>
  </p>

  <p><%= label_tag :helpdesk_ticket_source,  l(:label_helpdesk_ticket_source)%>
    <%= select_tag 'helpdesk_ticket[source]', options_for_select(helpdesk_tickets_source_for_select) %></p>

  <p class="required"><%= label_tag :helpdesk_ticket_date,  l(:label_helpdesk_ticket_date)%>
    <%= text_field_tag 'helpdesk_ticket[ticket_date]', Date.today, :size => 12 %> <%= text_field_tag 'helpdesk_ticket[ticket_time]', Time.now.to_s(:time), :size => 5 %><%= calendar_for('helpdesk_ticket_ticket_date') %> </p>


<% end %>